{% set name = "webedge" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/WebEdge-{{ version }}.tar.gz
  sha256: 781e7f32a792348ca8aecc38f19e116342add611d7c4108f184f9c9d0f53d5b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python <3.10
  run:
    - python <3.10
    - appdirs ==1.4.3
    - beautifulsoup4 ==4.9.3
    - bs4 ==0.0.1
    - cachecontrol ==0.12.6
    - certifi ==2019.11.28
    - chardet ==3.0.4
    - clanimate ==0.0.1
    - click ==7.1.2
    - colorama ==0.4.4
    - contextlib2 ==0.6.0
    - distlib ==0.3.0
    - distro ==1.4.0
    - html5lib ==1.0.1
    - idna ==2.8
    - ipaddr ==2.2.0
    - joblib ==0.17.0
    - lockfile ==0.12.2
    - msgpack-python ==0.6.2
    - nltk ==3.5
    - packaging ==20.3
    - pep517 ==0.8.2
    - progress ==1.5
    - prompt-toolkit ==1.0.14
    - pyfiglet ==0.8.post1
    - pygments ==2.7.2
    - pyinquirer ==1.0.3
    - pyparsing ==2.4.6
    - python
    - pytoml ==0.1.21
    - pyyaml ==5.3.1
    - regex ==2020.11.13
    - requests ==2.25.0
    - retrying ==1.3.3
    - sentimentanalysis ==0.8
    - six ==1.15.0
    - soupsieve ==2.0.1
    - tqdm ==4.53.0
    - urllib3 ==1.26.2
    - vadersentiment ==3.3.2
    - wcwidth ==0.2.5
    - webencodings ==0.5.1

test:
  imports:
    - webedge
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/HarshCasper/WebEdge
  summary: Bringing Edge to your Web Performance
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HarshCasper
